Switch to std::bind
ros-controls/control_toolbox pull request #117
Opened 2022-01-26 10:56 UTC by jspricke

2022-01-27 08:38 UTC, destogl approved these changes
Looking good to me!

2022-05-05 17:01 UTC, bmagyar requested changes
actually... not for melodic, sorry

let me create a master branch or something else wehre new stuff can go to

2022-05-05 17:04 UTC, jspricke commented
std::bind is part of C++11 so should be fine in melodic, right? https://en.cppreference.com/w/cpp/utility/functional/bind

2022-05-10 09:36 UTC, bmagyar approved these changes

2022-05-10 09:39 UTC, merged