[PID] Add support for saving i-term when PID is reset
ros-controls/control_toolbox pull request #180
Opened 2024-02-11 08:19 UTC by destogl

Saves integral term on reset to maintain steady state offset output.
This is required for controlling of system without integral part to achieve correct steady-state output.
If intergral term is reset for some time there will be incorrect output in steady-state. This features avoids such situations and makes btter performance.

2024-02-11 11:09 UTC, olivier-stasse approved these changes
LGTM

2024-04-04 19:25 UTC, christophfroehlich requested changes
There is no test if this parameter has the desired effect. Could you please add any? e.g., to `gainSettingCopyPIDTest` or add a new one..

2025-01-11 21:25 UTC, christophfroehlich approved these changes
I added a test for this functionality to `integralOnlyTest`

2025-01-11 21:29 UTC, christophfroehlich approved these changes

2025-01-12 21:18 UTC, saikishor requested changes
The changes in the PR look fine to me, just some minor changes here

Apart from that, just a conceptual question. I'm not sure if the `save_i_term` should be the part of the Gains itself or it should be a parameter to the `reset` method alone. If everyone is happy with the original choice, I'm fine with it.

2025-01-23 12:27 UTC, christophfroehlich approved these changes
I applied the changes requested by @saikishor and had a focus on not breaking ABI -> check is green -> we can merge that into jazzy imho.

2025-01-23 13:17 UTC, saikishor approved these changes
In general, LGTM

2025-01-23 13:17 UTC, saikishor commented on include/control_toolbox/pid.hpp
>     */
```suggestion
   * @note The integral term is not retained and it is reset to zero
   */
```

Just to document

2025-01-23 13:17 UTC, saikishor commented on include/control_toolbox/pid_ros.hpp
>     */
```suggestion
   * @note The integral term is not retained and it is reset to zero
   */
```

2025-01-23 13:17 UTC, saikishor commented on include/control_toolbox/pid_ros.hpp
> +  void reset(bool save_iterm = false);
```suggestion
  void reset(bool save_iterm);
```

It is better to remove the default arg, I'm not sure how the compiler can differentiate between the non parsed one and the default param one

2025-01-23 13:17 UTC, saikishor commented on src/pid.cpp
> +  }
Do we need this check?

2025-01-23 13:31 UTC, christophfroehlich commented on include/control_toolbox/pid_ros.hpp
> +  void reset(bool save_iterm = false);
it did not complain although I have used both versions in the tests. but it is not really necessary here.

2025-01-23 13:32 UTC, christophfroehlich commented on src/pid.cpp
> +  }
maybe not? it does not take more effort to just zero it.

2025-01-23 13:32 UTC, christophfroehlich commented on src/pid.cpp
> +  }
```suggestion
```

2025-01-23 13:33 UTC, christophfroehlich commented on src/pid.cpp
> +  }
in the earlier version we had to use the RT buffer here, that's why

2025-01-23 13:38 UTC, saikishor commented on src/pid.cpp
> +  }
Got it

2025-01-23 13:39 UTC, saikishor approved these changes

2025-01-23 13:56 UTC, christophfroehlich approved these changes

2025-01-23 13:57 UTC, merged